language: node_js

node_js:
  - "node"
  - "6.4"
  - "5.3"
  - "4.2"
  - "iojs"
  - "0.12"
  
os:
  - linux
#  - osx

before_install:
  - pwd
#  - rm -rf ~/.nvm
#  - git clone https://github.com/creationix/nvm.git !/.nvm
#  - source ~/.nvm/nvm.sh

addons:
  code_climate:
    repo_token: f50b5c7ebd68103f6233b46602a1607896b8ddcfe25355a11d865aa5acd60758
after_script:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
