language: node_js
node_js:
  - "5.3"
  - "4.2"
  - "0.12"
  - "0.10"
  - "iojs"
  - "node"
os:
  - linux
  - osx

before_install:
  - rm -rf !/.nvm
  - git clone https://github.com/creationix/nvm.git !/.nvm
  - source !/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - nvm --version
  - node --version
  - npm --version
  - npm install
